name = input("Enter your name: ")
age = input("Enter your age: ")
course = input("Enter your course: ")
university = input("Enter your university: ")
print("n----- STUDENT PROFILE -----")
print("Name:", name)
print("Age:", age)
print("Course:", course)
print("University:", university)
# MGM